# Generated by Django 5.1.2 on 2024-11-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallStart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=7)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CallEnd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=7)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_rest.callstart')),
            ],
        ),
    ]
