# Generated by Django 5.1.2 on 2024-11-04 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_remove_callend_call_id_callend_call_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callend',
            name='call_start',
        ),
        migrations.AddField(
            model_name='callend',
            name='call_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='call_id_end', to='api_rest.callstart'),
        ),
        migrations.AlterField(
            model_name='callend',
            name='call_type',
            field=models.CharField(default='END', max_length=7),
        ),
        migrations.AlterField(
            model_name='callstart',
            name='call_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='call_id_start', to='api_rest.callend'),
        ),
        migrations.AlterField(
            model_name='callstart',
            name='call_type',
            field=models.CharField(default='START', max_length=7),
        ),
    ]
