# Generated by Django 5.1.2 on 2024-11-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_remove_callend_call_start_callend_call_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstart',
            name='call_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
