# Generated by Django 5.1.2 on 2024-11-05 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_callstart_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callend',
            name='call_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_rest.callstart', to_field='call_id'),
        ),
    ]
