# Generated by Django 5.1.2 on 2024-11-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_alter_callend_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstart',
            name='call_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
